import { useAuthStore } from "../store/AuthStore";

export const useAuth = () => {
  const {
    register,
    logout,
    login,
    currentUser,
    currentRole,
    accessToken,
    status,
    subjectDetails,
    sclassDetails,
    sclassStudents,
    getSubjectDetails,
    getClassDetails,
    getClassStudents,
    getAllStudents,
    getAllSclasses,
    getAllTeachers,
    studentsList,
    sclasses,
    error,
    getresponse,
    loading,
    tempDetails: details,
    addStuff,
    resetAuthStatus,
    getSubjectList,
    subjectsList,
    updateUser,
    getUserDetails,
    userDetails,
    deleteUser,
    complainList,
    getAllComplains,
  } = useAuthStore((state) => ({
    register: state.register,
    login: state.login,
    logout: state.logout,
    currentUser: state.currentUser,
    currentRole: state.currentRole,
    accessToken: state.accessToken,
    status: state.status,
    subjectDetails: state.subjectDetails,
    sclassDetails: state.sclassDetails,
    sclassStudents: state.sclassStudents,
    getSubjectDetails: state.getSubjectDetails,
    getClassDetails: state.getClassDetails,
    getClassStudents: state.getClassStudents,
    getAllStudents: state.getAllStudents,
    getAllSclasses: state.getAllSclasses,
    getAllTeachers: state.getAllTeachers,
    userDetails: state.userDetails,
    tempDetails: state.tempDetails,
    error: state.error,
    loading: state.loading,
    getresponse: state.response,
    details: state.tempDetails,
    addStuff: state.addStuff,
    resetAuthStatus: state.resetAuthStatus,
    getSubjectList: state.getSubjectList,
    subjectsList: state.subjectList,
    sclasses: state.sclasses,
    studentsList: state.studentsList,
    updateUser: state.updateUser,
    getUserDetails: state.getUserDetails,
    deleteUser: state.deleteUser,
    complainList: state.complainList,
    getAllComplains: state.getAllComplains,
  }));

  return {
    register,
    login,
    logout,
    currentUser,
    currentRole,
    accessToken,
    status,
    subjectDetails,
    sclassDetails,
    sclassStudents,
    getSubjectDetails,
    getClassDetails,
    getClassStudents,
    studentsList,
    sclasses,
    getAllStudents,
    getAllSclasses,
    getAllTeachers,
    error,
    getresponse,
    loading,
    details,
    addStuff,
    resetAuthStatus,
    getSubjectList,
    subjectsList,
    updateUser,
    getUserDetails,
    userDetails,
    deleteUser,
    complainList,
    getAllComplains,
  };
};
