import { useAuthStore } from "../store/AuthStore";

export const useAuth = () => {
  const {
    register,
    logout,
    login,
    currentUser,
    currentRole,
    accessToken,
    status,
    subjectDetails,
    sclassStudents,
    getSubjectDetails,
    getClassStudents,
    getAllStudents,
    getAllSclasses,
    getAllTeachers,
    userDetails: studentsList,
    tempDetails: sclassesList,
    error,
    getresponse,
    loading,
  } = useAuthStore((state) => ({
    register: state.register,
    login: state.login,
    logout: state.logout,
    currentUser: state.currentUser,
    currentRole: state.currentRole,
    accessToken: state.accessToken,
    status: state.status,
    subjectDetails: state.subjectDetails,
    sclassStudents: state.sclassStudents,
    getSubjectDetails: state.getSubjectDetails,
    getClassStudents: state.getClassStudents,
    getAllStudents: state.getAllStudents,
    getAllSclasses: state.getAllSclasses,
    getAllTeachers: state.getAllTeachers,
    userDetails: state.userDetails,
    tempDetails: state.tempDetails,
    error: state.error,
    loading: state.loading,
    getresponse: state.response,
  }));

  return {
    register,
    login,
    logout,
    currentUser,
    currentRole,
    accessToken,
    status,
    subjectDetails,
    sclassStudents,
    getSubjectDetails,
    getClassStudents,
    studentsList,
    sclassesList,
    getAllStudents,
    getAllSclasses,
    getAllTeachers,
    error,
    getresponse,
    loading,
  };
};
