import { useAuthStore } from "../store/AuthStore";

export const useAuth = () => {
  const {
    register,
    logout,
    login,
    currentUser,
    currentRole,
    accessToken,
    getstatus,
    subjectDetails,
    sclassDetails,
    sclassStudents,
    getSubjectDetails,
    getClassDetails,
    getClassStudents,
    getAllTeachers,
    getAllParents,
    getAllStudents,
    getAllSclasses,
    teachersList,
    parentsList,
    studentsList,
    sclasses,
    error,
    getresponse,
    loading,
    tempDetails: details,
    addStuff,
    resetAuthStatus,
    getSubjectList,
    subjectsList,
    updateUser,
    removeAtten,
    getUserDetails,
    userDetails,
    deleteUser,
    complainList,
    getAllComplains,
    noticeList,
    getAllNotices,
    getTeacherDetails,
    teacherDetails,
    getTeacherFreeClassSubjects,
    updateTeachSubject,
    updateStudentFields,
    updateExamResults,
    enrollSubject,
    dropSubject,
    setFee,
    processFee,
    feeData,
    getFee,
    fee,
    resetPassword,
    verifyResetCode,
    forgotPassword,
    getEnrolledSubjects,
    enrolledSubjects,
    getAvailableSubjects,
    availableSubjects,
  } = useAuthStore((state) => ({
    register: state.register,
    login: state.login,
    logout: state.logout,
    currentUser: state.currentUser,
    currentRole: state.currentRole,
    accessToken: state.accessToken,
    getstatus: state.status,
    subjectDetails: state.subjectDetails,
    sclassDetails: state.sclassDetails,
    sclassStudents: state.sclassStudents,
    getSubjectDetails: state.getSubjectDetails,
    getClassDetails: state.getClassDetails,
    getClassStudents: state.getClassStudents,
    getAllStudents: state.getAllStudents,
    getAllSclasses: state.getAllSclasses,
    getAllTeachers: state.getAllTeachers,
    getAllParents: state.getAllParents,
    userDetails: state.userDetails,
    tempDetails: state.tempDetails,
    error: state.error,
    loading: state.loading,
    getresponse: state.response,
    details: state.tempDetails,
    addStuff: state.addStuff,
    resetAuthStatus: state.resetAuthStatus,
    getSubjectList: state.getSubjectList,
    subjectsList: state.subjectsList,
    sclasses: state.sclasses,
    teachersList: state.teachersList,
    parentsList: state.parentsList,
    studentsList: state.studentsList,
    updateUser: state.updateUser,
    removeAtten: state.removeAtten,
    getUserDetails: state.getUserDetails,
    deleteUser: state.deleteUser,
    complainList: state.complainList,
    getAllComplains: state.getAllComplains,
    noticeList: state.noticeList,
    getAllNotices: state.getAllNotices,
    teacherDetails: state.teacherDetails,
    getTeacherDetails: state.getTeacherDetails,
    getTeacherFreeClassSubjects: state.getTeacherFreeClassSubjects,
    updateTeachSubject: state.updateTeachSubject,
    updateStudentFields: state.updateStudentFields,
    updateExamResults: state.updateExamResults,
    enrollSubject: state.enrollSubject,
    dropSubject: state.dropSubject,
    setFee: state.setFee,
    processFee: state.processFee,
    feeData: state.feeData,
    getFee: state.getFee,
    fee: state.fee,
    resetPassword: state.resetPassword,
    verifyResetCode: state.verifyResetCode,
    forgotPassword: state.forgotPassword,
    getEnrolledSubjects: state.getEnrolledSubjects,
    enrolledSubjects: state.enrolledSubjects,
    getAvailableSubjects: state.getAvailableSubjects,
    availableSubjects: state.availableSubjects,
  }));

  return {
    register,
    login,
    logout,
    currentUser,
    currentRole,
    accessToken,
    getstatus,
    subjectDetails,
    sclassDetails,
    sclassStudents,
    getSubjectDetails,
    getClassDetails,
    getClassStudents,
    teachersList,
    parentsList,
    studentsList,
    sclasses,
    getAllTeachers,
    getAllParents,
    getAllStudents,
    getAllSclasses,
    error,
    getresponse,
    loading,
    details,
    addStuff,
    resetAuthStatus,
    getSubjectList,
    subjectsList,
    updateUser,
    removeAtten,
    getUserDetails,
    userDetails,
    deleteUser,
    complainList,
    getAllComplains,
    noticeList,
    getAllNotices,
    teacherDetails,
    getTeacherDetails,
    getTeacherFreeClassSubjects,
    updateTeachSubject,
    updateStudentFields,
    updateExamResults,
    enrollSubject,
    dropSubject,
    setFee,
    processFee,
    feeData,
    getFee,
    fee,
    resetPassword,
    verifyResetCode,
    forgotPassword,
    getEnrolledSubjects,
    enrolledSubjects,
    getAvailableSubjects,
    availableSubjects,
  };
};
